import { Question } from '../types/quiz';

const MEDIUM_BASE_ID = 300; // Starting ID for medium questions

export const mediumQuestions: Question[] = [
  {
    "id": MEDIUM_BASE_ID + 1,
    "question": "What is the relationship between frequency and wavelength in a sound wave?",
    "answerChoices": [
      "Frequency is inversely proportional to wavelength",
      "Frequency and wavelength are directly proportional",
      "Frequency does not affect wavelength",
      "Frequency is equal to wavelength"
    ],
    "correctAnswer": 0,
    "difficulty": "medium",
    "category": "physics"
  },
  {
    "id": MEDIUM_BASE_ID + 2,
    "question": "What is the standard reference level for 0 dB SPL?",
    "answerChoices": [
      "20 µPa",
      "2 Pa",
      "200 µPa",
      "2 mPa"
    ],
    "correctAnswer": 0,
    "difficulty": "medium",
    "category": "fundamentals"
  },
  {
    "id": MEDIUM_BASE_ID + 3,
    "question": "What is the purpose of dithering in digital audio processing?",
    "answerChoices": [
      "Reduce quantization errors",
      "Compress the audio signal",
      "Add reverb to a signal",
      "Boost the high frequencies"
    ],
    "correctAnswer": 0,
    "difficulty": "medium",
    "category": "dsp"
  },
  {
    "id": MEDIUM_BASE_ID + 4,
    "question": "Which of the following describes the 'Nyquist frequency'?",
    "answerChoices": [
      "Half the sampling rate",
      "Twice the sampling rate",
      "The maximum bit depth",
      "The standard audio file size"
    ],
    "correctAnswer": 0,
    "difficulty": "medium",
    "category": "fundamentals"
  },
  {
    "id": MEDIUM_BASE_ID + 5,
    "question": "What is the function of a comb filter?",
    "answerChoices": [
      "Create a series of notches in the frequency spectrum",
      "Boost low frequencies",
      "Add reverb to a signal",
      "Remove high frequencies"
    ],
    "correctAnswer": 0,
    "difficulty": "medium",
    "category": "dsp"
  },
  {
    "id": MEDIUM_BASE_ID + 6,
    "question": "What is the term for frequencies generated by non-linearities in a sound system?",
    "answerChoices": [
      "Harmonic distortion",
      "Phase shift",
      "Reverberation",
      "Transient response"
    ],
    "correctAnswer": 0,
    "difficulty": "medium",
    "category": "physics"
  },
  {
    "id": MEDIUM_BASE_ID + 7,
    "question": "What does the attack parameter in a compressor control?",
    "answerChoices": [
      "How quickly the compressor begins to reduce the signal",
      "The level at which compression starts",
      "The amount of gain applied after compression",
      "The time it takes for the compression to stop"
    ],
    "correctAnswer": 0,
    "difficulty": "medium",
    "category": "dsp"
  },
  {
    "id": MEDIUM_BASE_ID + 8,
    "question": "Which phenomenon explains the masking of one sound by another of a similar frequency?",
    "answerChoices": [
      "Frequency masking",
      "Phase cancellation",
      "Harmonic interference",
      "Acoustic shadowing"
    ],
    "correctAnswer": 0,
    "difficulty": "medium",
    "category": "psychoacoustics"
  },
  {
    "id": MEDIUM_BASE_ID + 9,
    "question": "What does the term 'headroom' refer to in audio systems?",
    "answerChoices": [
      "The difference between nominal operating level and clipping point",
      "The space between the microphones in stereo recording",
      "The frequency range of a sound system",
      "The length of the reverb tail in a mix"
    ],
    "correctAnswer": 0,
    "difficulty": "medium",
    "category": "fundamentals"
  },
  {
    "id": MEDIUM_BASE_ID + 10,
    "question": "What is the primary purpose of an all-pass filter?",
    "answerChoices": [
      "Modify phase without altering amplitude",
      "Increase gain at specific frequencies",
      "Remove noise from a signal",
      "Boost low frequencies in the mix"
    ],
    "correctAnswer": 0,
    "difficulty": "medium",
    "category": "dsp"
  },
  {
    "id": MEDIUM_BASE_ID + 11,
    "question": "Which of the following best describes binaural audio?",
    "answerChoices": [
      "Audio designed to simulate 3D spatial hearing",
      "Audio with enhanced low frequencies",
      "Audio with multiple reverberation layers",
      "Mono audio converted to stereo"
    ],
    "correctAnswer": 0,
    "difficulty": "medium",
    "category": "psychoacoustics"
  },
  {
    "id": MEDIUM_BASE_ID + 12,
    "question": "What is a common use for a parametric equalizer?",
    "answerChoices": [
      "Precisely adjust frequency bands with control over bandwidth",
      "Remove noise from an audio signal",
      "Create a stereo imaging effect",
      "Boost the overall volume of a track"
    ],
    "correctAnswer": 0,
    "difficulty": "medium",
    "category": "dsp"
  },
  {
    "id": MEDIUM_BASE_ID + 13,
    "question": "What is the main cause of phase cancellation in audio?",
    "answerChoices": [
      "Two identical waves being out of phase",
      "High levels of harmonic distortion",
      "Incorrect application of a limiter",
      "Over-compression in the dynamic range"
    ],
    "correctAnswer": 0,
    "difficulty": "medium",
    "category": "physics"
  },
  {
    "id": MEDIUM_BASE_ID + 14,
    "question": "What does an envelope generator control in a synthesizer?",
    "answerChoices": [
      "The amplitude over time",
      "The harmonic content of a waveform",
      "The pitch of the oscillator",
      "The stereo placement of the sound"
    ],
    "correctAnswer": 0,
    "difficulty": "medium",
    "category": "electronic music"
  },
  {
    "id": MEDIUM_BASE_ID + 15,
    "question": "What does a low-frequency oscillator (LFO) typically modulate in sound synthesis?",
    "answerChoices": [
      "Parameters such as pitch, volume, or filter cutoff",
      "The bit depth of the audio file",
      "The frequency response of a signal",
      "The headroom of the audio chain"
    ],
    "correctAnswer": 0,
    "difficulty": "medium",
    "category": "electronic music"
  },
  {
    "id": MEDIUM_BASE_ID + 16,
    "question": "What is the primary purpose of sidechain compression?",
    "answerChoices": [
      "Duck the level of one signal in response to another",
      "Reduce noise in the signal path",
      "Enhance stereo imaging",
      "Add harmonic content to low frequencies"
    ],
    "correctAnswer": 0,
    "difficulty": "medium",
    "category": "dsp"
  },
  {
    "id": MEDIUM_BASE_ID + 17,
    "question": "What does the Haas effect describe?",
    "answerChoices": [
      "The perception of spatial location based on timing differences",
      "The interference of two sound waves of the same frequency",
      "The increase in amplitude due to harmonic resonance",
      "The blending of multiple echoes into a reverb tail"
    ],
    "correctAnswer": 0,
    "difficulty": "medium",
    "category": "psychoacoustics"
  },
  {
    "id": MEDIUM_BASE_ID + 18,
    "question": "What is the primary role of a preamplifier in an audio signal chain?",
    "answerChoices": [
      "Boost the signal level to line level",
      "Reduce background noise",
      "Apply equalization to the signal",
      "Convert analog signals to digital"
    ],
    "correctAnswer": 0,
    "difficulty": "medium",
    "category": "hardware"
  },
  {
    "id": MEDIUM_BASE_ID + 19,
    "question": "What is a polar pattern in a microphone?",
    "answerChoices": [
      "The directional sensitivity of the microphone",
      "The frequency response curve of the microphone",
      "The signal-to-noise ratio of the microphone",
      "The impedance level of the microphone"
    ],
    "correctAnswer": 0,
    "difficulty": "medium",
    "category": "hardware"
  },
  {
    "id": MEDIUM_BASE_ID + 20,
    "question": "What is the function of a crossover in a speaker system?",
    "answerChoices": [
      "Divide audio signals into frequency bands for different drivers",
      "Increase overall system volume",
      "Reduce unwanted background noise",
      "Balance the stereo field"
    ],
    "correctAnswer": 0,
    "difficulty": "medium",
    "category": "hardware"
  },
  {
    "id": MEDIUM_BASE_ID + 21,
    "question": "Which type of distortion occurs when the input level exceeds the system's maximum capacity?",
    "answerChoices": [
      "Clipping distortion",
      "Harmonic distortion",
      "Phase distortion",
      "Transient distortion"
    ],
    "correctAnswer": 0,
    "difficulty": "medium",
    "category": "dsp"
  },
  {
    "id": MEDIUM_BASE_ID + 22,
    "question": "What is an impulse response used for in acoustics?",
    "answerChoices": [
      "Measure the characteristics of a space or system",
      "Add reverb effects",
      "Analyze phase cancellation",
      "Create a stereo widening effect"
    ],
    "correctAnswer": 0,
    "difficulty": "medium",
    "category": "acoustics"
  },
  {
    "id": MEDIUM_BASE_ID + 23,
    "question": "What is the primary purpose of a de-esser?",
    "answerChoices": [
      "Reduce sibilant sounds in vocals",
      "Add harmonic warmth to a mix",
      "Compress dynamic range",
      "Eliminate low-frequency rumble"
    ],
    "correctAnswer": 0,
    "difficulty": "medium",
    "category": "dsp"
  },
  {
    "id": MEDIUM_BASE_ID + 24,
    "question": "What is the significance of a 'null' in a cardioid microphone's polar pattern?",
    "answerChoices": [
      "Indicates the least sensitive direction",
      "Indicates the frequency response peak",
      "Represents the maximum gain point",
      "Represents the maximum distortion area"
    ],
    "correctAnswer": 0,
    "difficulty": "medium",
    "category": "hardware"
  },
  {
    "id": MEDIUM_BASE_ID + 25,
    "question": "What is the main advantage of a balanced audio cable?",
    "answerChoices": [
      "It reduces electromagnetic interference and noise",
      "It provides higher frequency response",
      "It increases audio volume",
      "It eliminates phase shifts"
    ],
    "correctAnswer": 0,
    "difficulty": "medium",
    "category": "hardware"
  },
  {
    "id": MEDIUM_BASE_ID + 26,
    "question": "What does 'bit depth' determine in a digital audio signal?",
    "answerChoices": [
      "The dynamic range of the audio",
      "The frequency response of the signal",
      "The speed of the audio playback",
      "The stereo width of the mix"
    ],
    "correctAnswer": 0,
    "difficulty": "medium",
    "category": "fundamentals"
  },
  {
    "id": MEDIUM_BASE_ID + 27,
    "question": "What is the typical latency range for live audio monitoring?",
    "answerChoices": [
      "Below 10 ms",
      "20-50 ms",
      "50-100 ms",
      "Over 100 ms"
    ],
    "correctAnswer": 0,
    "difficulty": "medium",
    "category": "hardware"
  },
  {
    "id": MEDIUM_BASE_ID + 28,
    "question": "Which physical principle explains the directional nature of high-frequency sound waves?",
    "answerChoices": [
      "Shorter wavelengths result in less diffraction",
      "Longer wavelengths reflect more easily",
      "Higher frequencies have lower energy",
      "Sound speed increases with higher frequencies"
    ],
    "correctAnswer": 0,
    "difficulty": "medium",
    "category": "physics"
  },
  {
    "id": MEDIUM_BASE_ID + 29,
    "question": "What is the primary function of a convolution reverb?",
    "answerChoices": [
      "Simulate a specific acoustic space using an impulse response",
      "Apply a synthetic reverb effect",
      "Control the dynamic range of a mix",
      "Enhance stereo imaging"
    ],
    "correctAnswer": 0,
    "difficulty": "medium",
    "category": "dsp"
  },
  {
    "id": MEDIUM_BASE_ID + 30,
    "question": "What does the Fletcher-Munson curve describe?",
    "answerChoices": [
      "Human sensitivity to different frequencies at varying loudness levels",
      "The relationship between frequency and wavelength",
      "The interference patterns of two sound waves",
      "The absorption characteristics of acoustic materials"
    ],
    "correctAnswer": 0,
    "difficulty": "medium",
    "category": "psychoacoustics"
  },
  {
    "id": MEDIUM_BASE_ID + 31,
    "question": "Which of the following is true about phase alignment in a multi-microphone setup?",
    "answerChoices": [
      "It reduces phase cancellation and ensures coherent summation",
      "It increases the dynamic range of the recording",
      "It enhances the stereo width of the audio",
      "It eliminates noise in the audio signal"
    ],
    "correctAnswer": 0,
    "difficulty": "medium",
    "category": "acoustics"
  },
  {
    "id": MEDIUM_BASE_ID + 32,
    "question": "What is a decibel (dB) a measure of in sound?",
    "answerChoices": [
      "A logarithmic ratio of sound intensity",
      "The speed of sound",
      "The frequency of a sound wave",
      "The amplitude of a waveform"
    ],
    "correctAnswer": 0,
    "difficulty": "medium",
    "category": "fundamentals"
  },
  {
    "id": MEDIUM_BASE_ID + 33,
    "question": "What is the main advantage of using a cardioid microphone in live sound?",
    "answerChoices": [
      "It minimizes feedback by rejecting rear sound",
      "It captures sound equally from all directions",
      "It emphasizes high-frequency content",
      "It eliminates the need for phantom power"
    ],
    "correctAnswer": 0,
    "difficulty": "medium",
    "category": "hardware"
  },
  {
    "id": MEDIUM_BASE_ID + 34,
    "question": "What is the function of a parametric equalizer's Q setting?",
    "answerChoices": [
      "Control the bandwidth of the affected frequency range",
      "Adjust the overall output gain",
      "Set the low-pass filter frequency",
      "Define the resonance of the low frequencies"
    ],
    "correctAnswer": 0,
    "difficulty": "medium",
    "category": "dsp"
  },
  {
    "id": MEDIUM_BASE_ID + 35,
    "question": "What is 'critical distance' in room acoustics?",
    "answerChoices": [
      "The distance at which direct sound and reflected sound levels are equal",
      "The point where sound intensity drops by half",
      "The maximum distance a microphone can capture sound",
      "The minimum distance required for sound to travel without reflection"
    ],
    "correctAnswer": 0,
    "difficulty": "medium",
    "category": "acoustics"
  },
  {
    "id": MEDIUM_BASE_ID + 36,
    "question": "What is the purpose of a sidechain in audio processing?",
    "answerChoices": [
      "Allow an external signal to trigger an effect",
      "Remove unwanted noise from the main signal",
      "Enhance stereo width",
      "Compress high-frequency content"
    ],
    "correctAnswer": 0,
    "difficulty": "medium",
    "category": "dsp"
  },
  {
    "id": MEDIUM_BASE_ID + 37,
    "question": "What is the difference between balanced and unbalanced cables?",
    "answerChoices": [
      "Balanced cables reduce noise by using phase inversion",
      "Balanced cables increase frequency response",
      "Unbalanced cables require less voltage",
      "Unbalanced cables provide superior signal quality"
    ],
    "correctAnswer": 0,
    "difficulty": "medium",
    "category": "hardware"
  },
  {
    "id": MEDIUM_BASE_ID + 38,
    "question": "Which of these filters allows frequencies within a specific range to pass through?",
    "answerChoices": [
      "Band-pass filter",
      "High-pass filter",
      "Low-pass filter",
      "Notch filter"
    ],
    "correctAnswer": 0,
    "difficulty": "medium",
    "category": "dsp"
  },
  {
    "id": MEDIUM_BASE_ID + 39,
    "question": "What is the effect of using a limiter on an audio track?",
    "answerChoices": [
      "Prevent signal peaks from exceeding a set threshold",
      "Boost low-level signals",
      "Reduce background noise",
      "Add harmonic distortion to the signal"
    ],
    "correctAnswer": 0,
    "difficulty": "medium",
    "category": "dsp"
  },
  {
    "id": MEDIUM_BASE_ID + 40,
    "question": "What does the term 'impulse response' refer to in digital audio?",
    "answerChoices": [
      "A recording of a system’s reaction to an impulse",
      "The response of a microphone to low frequencies",
      "The decay time of a reverb effect",
      "The latency of an audio interface"
    ],
    "correctAnswer": 0,
    "difficulty": "medium",
    "category": "acoustics"
  },
  {
    "id": MEDIUM_BASE_ID + 41,
    "question": "Which microphone polar pattern is most sensitive to sound from all directions?",
    "answerChoices": [
      "Omnidirectional",
      "Cardioid",
      "Bidirectional",
      "Supercardioid"
    ],
    "correctAnswer": 0,
    "difficulty": "medium",
    "category": "hardware"
  },
  {
    "id": MEDIUM_BASE_ID + 42,
    "question": "What is aliasing in digital audio?",
    "answerChoices": [
      "An artifact caused by undersampling",
      "A delay caused by signal processing",
      "A phase shift between two signals",
      "A distortion from excessive gain"
    ],
    "correctAnswer": 0,
    "difficulty": "medium",
    "category": "dsp"
  },
  {
    "id": MEDIUM_BASE_ID + 43,
    "question": "What is an ADSR envelope?",
    "answerChoices": [
      "Attack, Decay, Sustain, Release",
      "Amplitude, Delay, Sustain, Resonance",
      "Audio, Dynamics, Spectrum, Resonance",
      "Attack, Duration, Sustain, Reverb"
    ],
    "correctAnswer": 0,
    "difficulty": "medium",
    "category": "electronic music"
  },
  {
    "id": MEDIUM_BASE_ID + 44,
    "question": "What is the primary advantage of using convolution reverb?",
    "answerChoices": [
      "It accurately replicates real acoustic spaces",
      "It reduces the dynamic range of the mix",
      "It creates artificial reverberation",
      "It eliminates phase distortion"
    ],
    "correctAnswer": 0,
    "difficulty": "medium",
    "category": "dsp"
  },
  {
    "id": MEDIUM_BASE_ID + 45,
    "question": "What is the function of an audio expander?",
    "answerChoices": [
      "Increase dynamic range by reducing low-level signals",
      "Reduce noise by cutting high frequencies",
      "Enhance reverb tails in a mix",
      "Compress high-level signals"
    ],
    "correctAnswer": 0,
    "difficulty": "medium",
    "category": "dsp"
  },
  {
    "id": MEDIUM_BASE_ID + 46,
    "question": "What is the function of a noise gate in audio processing?",
    "answerChoices": [
      "Mute signals below a certain threshold",
      "Boost low-frequency content",
      "Reduce reverb tails",
      "Compress dynamic range"
    ],
    "correctAnswer": 0,
    "difficulty": "medium",
    "category": "dsp"
  },
  {
    "id": MEDIUM_BASE_ID + 47,
    "question": "What is the primary factor that determines the speed of sound in a medium?",
    "answerChoices": [
      "The density and elasticity of the medium",
      "The frequency of the sound",
      "The amplitude of the wave",
      "The wavelength of the sound"
    ],
    "correctAnswer": 0,
    "difficulty": "medium",
    "category": "physics"
  },
  {
    "id": MEDIUM_BASE_ID + 48,
    "question": "Which filter type removes a narrow band of frequencies?",
    "answerChoices": [
      "Notch filter",
      "High-pass filter",
      "Band-pass filter",
      "Low-pass filter"
    ],
    "correctAnswer": 0,
    "difficulty": "medium",
    "category": "dsp"
  },
  {
    "id": MEDIUM_BASE_ID + 49,
    "question": "What is comb filtering caused by?",
    "answerChoices": [
      "Interference between delayed versions of the same signal",
      "Distortion from overdriven inputs",
      "Excessive reverb in a mix",
      "High-pass filtering applied multiple times"
    ],
    "correctAnswer": 0,
    "difficulty": "medium",
    "category": "acoustics"
  },
  {
    "id": MEDIUM_BASE_ID + 50,
    "question": "What does 'zero-latency monitoring' refer to?",
    "answerChoices": [
      "Real-time monitoring without perceptible delay",
      "Monitoring with minimized background noise",
      "Reducing high-frequency roll-off during playback",
      "Monitoring signals through outboard effects"
    ],
    "correctAnswer": 0,
    "difficulty": "medium",
    "category": "hardware"
  }
];
